### ISSUE TITLE
Counters are easily accidentaly reset

### ISSUE THREAD

**Issue by SebiderSushi** [MarcelJurtz/LifeCounter#25]
It seems that a single click already resets the life counters. This is rather unfortunate as it can happen quick and haphazardly.
The requirement of a long click or a dialog asking for confirmation might mitigate this risk.

**Comment by MarcelJurtz** [comment]
That's a great idea, I'll add that to my next release.

**Comment by MarcelJurtz** [comment]
Hey, I've just uploaded a new release to google play, which should be available for download soon. I added a new option to the settings where you can select to show a confirmation dialog when resetting the game. However, I left it as-is per default, so you'll have to opt-in.
